"""hsn code, tax rate, user approval, shop prop

Revision ID: d5c6d910c8bd
Revises: c9e6bb822e24
Create Date: 2026-07-11 12:38:16.455950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c6d910c8bd'
down_revision = 'c9e6bb822e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=16), nullable=True))

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=16), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('hsn_code')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('bill_line_items', schema=None) as batch_op:
        batch_op.drop_column('hsn_code')

    # ### end Alembic commands ###
